import { BiX } from "react-icons/bi";
import {
  Settings,
  CircleHelp,
  UsersRound,
  Bell,
  User,
  LogOut,
  Globe, 
  EllipsisVertical,
  Plus,
  Trash2, 
  Filter,
  Search, 
  RefreshCcw, 
  FileInput,
  ChevronLeft, 
  ChevronRight,
  Star,
  Briefcase,
  Share2,
  BookOpen,
  MessageCircle,
  Home, 
  Menu, 
  X,
  Eye,
  DownloadIcon, 
  UserRoundPenIcon,
  University,
  Calendar, 
  List, 
  HandCoins,  
  MessagesSquare, 
  CalendarDays,
  UserCircle,
  Phone, 
  Mail, 
  MoreHorizontal,
  MapPin,
  Sparkles,
  Loader2,
  Send, 
  Paperclip,
  Users, 
  GraduationCap, 
  DollarSign,
  UserPlus,
  ChevronDown,
  TrendingUp, 
  Clock, 
  CheckCircle,
  XCircle,
  FileText,
  Receipt,
  Printer,
  Upload,
  Check,
  AlertCircle,
  CheckCheck, 
  Info,
  MoreVertical,
  Download,
  EyeOff,
  Edit,
  Lock,
  Unlock,
  ClipboardList,
  School,
  Award,
  Building2,
  AlertTriangle, 
  RotateCcw,
  Shield,
  CreditCard,
  IdCard,
  BookMarked
} from "lucide-react";
import { IoIosAlert } from "react-icons/io";
import { TbFileText, TbPigOff, TbFileArrowRight } from "react-icons/tb";
import { LiaCoinsSolid, LiaPiggyBankSolid } from "react-icons/lia";
import { AiOutlineApi,  AiOutlineForm, AiOutlineClose, AiOutlineCheck } from "react-icons/ai";
import { PiWebhooksLogoLight, PiBookOpenThin } from "react-icons/pi";
import { FaCommentSms } from "react-icons/fa6";
import { BsBank, BsCashCoin } from "react-icons/bs";
import { MdOutlineUploadFile, MdFileDownload, MdOutlineFileDownload } from "react-icons/md";
import { IoMdArrowDropdown, IoMdArrowForward, IoIosClose } from "react-icons/io";
import { GrFormCheckmark } from "react-icons/gr";
import { IoBookOutline } from "react-icons/io5";
import { GoQuestion } from "react-icons/go";
import { MdArrowBack } from "react-icons/md";
import { HiOutlineTrash } from "react-icons/hi2";
import {UsersThree, Student, SuitcaseSimple} from "phosphor-react";
import { SiGoogleclassroom } from "react-icons/si";
import { FaRegFileAlt } from "react-icons/fa";
import { PiFilesLight } from "react-icons/pi";
import { LuUserCog } from "react-icons/lu";
import { BsExclamationCircle } from "react-icons/bs";

export {
  SiGoogleclassroom,
  Sparkles,
  Loader2,
  Send, 
  Paperclip,
  Phone, 
  MoreHorizontal,
  Printer,
  Upload,
  MapPin,
  BsExclamationCircle,
  AlertTriangle, 
  RotateCcw,
  Shield,
  BsCashCoin,
  CreditCard,
  BookMarked,
  IdCard,
  FaRegFileAlt,
  MoreVertical,
  Download,
  PiFilesLight,
  School,
  Award,
  Check,
  AlertCircle,
  CheckCheck, 
  Info,
  LuUserCog,
  IoIosClose,
  IoMdArrowForward,
  Building2,
  FileText,
  Receipt,
  UserPlus,
  ChevronDown,
  HiOutlineTrash,
  Briefcase,
  Share2,
  ClipboardList,
  MdArrowBack,
  TrendingUp, 
  Clock, 
  XCircle,
  CheckCircle,
  GoQuestion,
  PiBookOpenThin,
  IoBookOutline,
  GrFormCheckmark,
  MdOutlineFileDownload,
  TbFileArrowRight,
  Eye,
  AiOutlineClose,
  MdFileDownload,
  Filter,
  MdOutlineUploadFile,
  AiOutlineForm,
  Trash2,
  Plus,
  AiOutlineCheck,
  BiX,
  Settings,
  CircleHelp,
  UsersRound,
  Users, 
  GraduationCap, 
  DollarSign,
  Bell,
  User,
  LogOut,
  TbFileText, 
  TbPigOff,
  LiaCoinsSolid, 
  LiaPiggyBankSolid,
  AiOutlineApi,
  PiWebhooksLogoLight,
  FaCommentSms,
  BsBank,
  Globe, 
  EllipsisVertical,
  Search, 
  RefreshCcw, 
  FileInput,
  ChevronLeft, 
  ChevronRight,
  Mail,
  IoMdArrowDropdown,
  Home, 
  Menu, 
  X,
  IoIosAlert,
  Calendar, 
  List, 
  HandCoins,  
  MessagesSquare, 
  CalendarDays, 
  UsersThree, 
  Student, 
  SuitcaseSimple,
  DownloadIcon,
  UserRoundPenIcon,
  University,
  UserCircle,
  EyeOff,
  Star,
  BookOpen,
  MessageCircle,
  Edit,
  Lock,
  Unlock,
}