import { StudentFullProfile } from "./academic-history";

const generateSubjects = (grade: string, performanceLevel: "excellent" | "good" | "average" | "poor") => {
  const baseSubjects = [
    "Língua Portuguesa",
    "Matemática",
    "Ciências Naturais",
    "História",
    "Geografia",
    "Educação Física",
    "Educação Visual",
    "Inglês",
  ];

  const gradeMultiplier = {
    excellent: { min: 14, max: 20 },
    good: { min: 12, max: 16 },
    average: { min: 10, max: 14 },
    poor: { min: 6, max: 12 },
  };

  const range = gradeMultiplier[performanceLevel];

  return baseSubjects.map((subject) => {
    const firstTerm = Math.floor(Math.random() * (range.max - range.min + 1)) + range.min;
    const secondTerm = Math.floor(Math.random() * (range.max - range.min + 1)) + range.min;
    const thirdTerm = Math.floor(Math.random() * (range.max - range.min + 1)) + range.min;
    const finalGrade = Math.round((firstTerm + secondTerm + thirdTerm) / 3);

    return {
      subject,
      firstTerm,
      secondTerm,
      thirdTerm,
      finalGrade,
    };
  });
};

const calculateAverage = (subjects: { finalGrade: number }[]) => {
  const sum = subjects.reduce((acc, s) => acc + s.finalGrade, 0);
  return Math.round((sum / subjects.length) * 10) / 10;
};

export const mockStudentProfiles: StudentFullProfile[] = [
  {
    id: "1",
    name: "Maria Santos Silva",
    birthDate: new Date("2010-03-15"),
    gender: "F",
    nationality: "Angolana",
    documentNumber: "001234567LA045",
    documentType: "Bilhete de Identidade",
    address: "Rua da Esperança, nº 45, Talatona, Luanda",
    phone: "+244 923 456 789",
    email: "maria.santos@email.com",
    parentName: "João Santos",
    parentPhone: "+244 912 345 678",
    parentEmail: "joao.santos@email.com",
    enrollmentDate: new Date("2018-02-01"),
    currentSchool: "Colégio Pitágoras",
    currentGrade: "7ª Classe",
    currentClass: "7ºA",
    studentNumber: "2018/001234",
    academicHistory: [
      {
        year: "2024",
        grade: "7ª Classe",
        class: "7ºA",
        school: "Colégio Pitágoras",
        subjects: generateSubjects("7", "excellent"),
        average: 0,
        passed: true,
        observations: "Aluna exemplar com excelente desempenho académico.",
        attendanceRate: 98,
        totalClasses: 200,
        attendedClasses: 196,
      },
      {
        year: "2023",
        grade: "6ª Classe",
        class: "6ºA",
        school: "Colégio Pitágoras",
        subjects: generateSubjects("6", "excellent"),
        average: 0,
        passed: true,
        observations: "Participação ativa em atividades extracurriculares.",
        attendanceRate: 96,
        totalClasses: 200,
        attendedClasses: 192,
      },
      {
        year: "2022",
        grade: "5ª Classe",
        class: "5ºB",
        school: "Colégio Pitágoras",
        subjects: generateSubjects("5", "good"),
        average: 0,
        passed: true,
        observations: "Bom aproveitamento geral.",
        attendanceRate: 94,
        totalClasses: 200,
        attendedClasses: 188,
      },
      {
        year: "2021",
        grade: "4ª Classe",
        class: "4ºA",
        school: "Escola Primária Sol Nascente",
        subjects: generateSubjects("4", "good"),
        average: 0,
        passed: true,
        observations: "Transição do ensino primário com sucesso.",
        attendanceRate: 95,
        totalClasses: 180,
        attendedClasses: 171,
      },
      {
        year: "2020",
        grade: "3ª Classe",
        class: "3ºA",
        school: "Escola Primária Sol Nascente",
        subjects: generateSubjects("3", "good"),
        average: 0,
        passed: true,
        observations: "Desenvolvimento positivo na leitura e escrita.",
        attendanceRate: 92,
        totalClasses: 180,
        attendedClasses: 166,
      },
      {
        year: "2019",
        grade: "2ª Classe",
        class: "2ºB",
        school: "Escola Primária Sol Nascente",
        subjects: generateSubjects("2", "average"),
        average: 0,
        passed: true,
        observations: "Adaptação ao ambiente escolar.",
        attendanceRate: 90,
        totalClasses: 180,
        attendedClasses: 162,
      },
      {
        year: "2018",
        grade: "1ª Classe",
        class: "1ºA",
        school: "Escola Primária Sol Nascente",
        subjects: generateSubjects("1", "average"),
        average: 0,
        passed: true,
        observations: "Início do percurso escolar.",
        attendanceRate: 88,
        totalClasses: 180,
        attendedClasses: 158,
      },
    ],
    issuedDocuments: [
      {
        id: "doc1",
        type: "certificate",
        title: "Certificado de Habilitações - 6ª Classe",
        issuedDate: new Date("2023-12-15"),
        withGrades: true,
      },
      {
        id: "doc2",
        type: "declaration",
        title: "Declaração de Matrícula 2024",
        issuedDate: new Date("2024-02-10"),
        withGrades: false,
      },
    ],
  },
  {
    id: "2",
    name: "Pedro António Fernandes",
    birthDate: new Date("2009-07-22"),
    gender: "M",
    nationality: "Angolano",
    documentNumber: "002345678LA046",
    documentType: "Bilhete de Identidade",
    address: "Av. 4 de Fevereiro, nº 123, Ingombota, Luanda",
    phone: "+244 924 567 890",
    email: "pedro.fernandes@email.com",
    parentName: "António Fernandes",
    parentPhone: "+244 913 456 789",
    parentEmail: "antonio.fernandes@email.com",
    enrollmentDate: new Date("2017-02-01"),
    currentSchool: "Colégio Pitágoras",
    currentGrade: "8ª Classe",
    currentClass: "8ºB",
    studentNumber: "2017/002345",
    academicHistory: [
      {
        year: "2024",
        grade: "8ª Classe",
        class: "8ºB",
        school: "Colégio Pitágoras",
        subjects: generateSubjects("8", "good"),
        average: 0,
        passed: true,
        observations: "Bom desempenho em ciências exatas.",
        attendanceRate: 94,
        totalClasses: 200,
        attendedClasses: 188,
      },
      {
        year: "2023",
        grade: "7ª Classe",
        class: "7ºB",
        school: "Colégio Pitágoras",
        subjects: generateSubjects("7", "good"),
        average: 0,
        passed: true,
        observations: "Melhoria significativa em matemática.",
        attendanceRate: 92,
        totalClasses: 200,
        attendedClasses: 184,
      },
      {
        year: "2022",
        grade: "6ª Classe",
        class: "6ºA",
        school: "Colégio Pitágoras",
        subjects: generateSubjects("6", "average"),
        average: 0,
        passed: true,
        observations: "Necessita melhorar em língua portuguesa.",
        attendanceRate: 90,
        totalClasses: 200,
        attendedClasses: 180,
      },
      {
        year: "2021",
        grade: "6ª Classe",
        class: "6ºB",
        school: "Colégio Pitágoras",
        subjects: generateSubjects("6", "poor"),
        average: 0,
        passed: false,
        observations: "Reprovado por falta de aproveitamento. Recomenda-se apoio extra.",
        attendanceRate: 75,
        totalClasses: 200,
        attendedClasses: 150,
      },
      {
        year: "2020",
        grade: "5ª Classe",
        class: "5ºA",
        school: "Escola Secundária Aurora",
        subjects: generateSubjects("5", "average"),
        average: 0,
        passed: true,
        observations: "Transição para o ensino secundário.",
        attendanceRate: 88,
        totalClasses: 200,
        attendedClasses: 176,
      },
    ],
    issuedDocuments: [
      {
        id: "doc3",
        type: "transcript",
        title: "Pauta de Notas - 7ª Classe",
        issuedDate: new Date("2023-12-20"),
        withGrades: true,
      },
    ],
  },
  {
    id: "3",
    name: "Ana Carolina Mendes",
    birthDate: new Date("2011-11-08"),
    gender: "F",
    nationality: "Angolana",
    documentNumber: "003456789LA047",
    documentType: "Bilhete de Identidade",
    address: "Rua Comandante Che Guevara, nº 78, Maianga, Luanda",
    phone: "+244 925 678 901",
    email: "ana.mendes@email.com",
    parentName: "Carlos Mendes",
    parentPhone: "+244 914 567 890",
    parentEmail: "carlos.mendes@email.com",
    enrollmentDate: new Date("2019-02-01"),
    currentSchool: "Escola Secundária Aurora",
    currentGrade: "6ª Classe",
    currentClass: "6ºA",
    studentNumber: "2019/003456",
    academicHistory: [
      {
        year: "2024",
        grade: "6ª Classe",
        class: "6ºA",
        school: "Escola Secundária Aurora",
        subjects: generateSubjects("6", "excellent"),
        average: 0,
        passed: true,
        observations: "Destaque em todas as disciplinas. Representante de turma.",
        attendanceRate: 99,
        totalClasses: 200,
        attendedClasses: 198,
      },
      {
        year: "2023",
        grade: "5ª Classe",
        class: "5ºA",
        school: "Escola Secundária Aurora",
        subjects: generateSubjects("5", "excellent"),
        average: 0,
        passed: true,
        observations: "Melhor aluna da turma.",
        attendanceRate: 98,
        totalClasses: 200,
        attendedClasses: 196,
      },
      {
        year: "2022",
        grade: "4ª Classe",
        class: "4ºB",
        school: "Escola Primária Horizonte",
        subjects: generateSubjects("4", "excellent"),
        average: 0,
        passed: true,
        observations: "Excelente comportamento e aproveitamento.",
        attendanceRate: 97,
        totalClasses: 180,
        attendedClasses: 175,
      },
      {
        year: "2021",
        grade: "3ª Classe",
        class: "3ºA",
        school: "Escola Primária Horizonte",
        subjects: generateSubjects("3", "good"),
        average: 0,
        passed: true,
        observations: "Boa adaptação ao novo currículo.",
        attendanceRate: 95,
        totalClasses: 180,
        attendedClasses: 171,
      },
      {
        year: "2020",
        grade: "2ª Classe",
        class: "2ºA",
        school: "Escola Primária Horizonte",
        subjects: generateSubjects("2", "good"),
        average: 0,
        passed: true,
        observations: "Desenvolvimento consistente.",
        attendanceRate: 93,
        totalClasses: 180,
        attendedClasses: 167,
      },
      {
        year: "2019",
        grade: "1ª Classe",
        class: "1ºB",
        school: "Escola Primária Horizonte",
        subjects: generateSubjects("1", "average"),
        average: 0,
        passed: true,
        observations: "Início do percurso escolar com bom desempenho.",
        attendanceRate: 91,
        totalClasses: 180,
        attendedClasses: 164,
      },
    ],
    issuedDocuments: [
      {
        id: "doc4",
        type: "certificate",
        title: "Certificado de Conclusão do Ensino Primário",
        issuedDate: new Date("2022-12-18"),
        withGrades: true,
      },
      {
        id: "doc5",
        type: "declaration",
        title: "Declaração de Frequência 2024",
        issuedDate: new Date("2024-03-05"),
        withGrades: false,
      },
    ],
  },
  {
    id: "4",
    name: "José Manuel Sousa",
    birthDate: new Date("2008-05-30"),
    gender: "M",
    nationality: "Angolano",
    documentNumber: "004567890LA048",
    documentType: "Bilhete de Identidade",
    address: "Rua Amílcar Cabral, nº 200, Maculusso, Luanda",
    phone: "+244 926 789 012",
    email: "jose.sousa@email.com",
    parentName: "Manuel Sousa",
    parentPhone: "+244 915 678 901",
    parentEmail: "manuel.sousa@email.com",
    enrollmentDate: new Date("2016-02-01"),
    currentSchool: "Escola Secundária Aurora",
    currentGrade: "9ª Classe",
    currentClass: "9ºA",
    studentNumber: "2016/004567",
    academicHistory: [
      {
        year: "2024",
        grade: "9ª Classe",
        class: "9ºA",
        school: "Escola Secundária Aurora",
        subjects: generateSubjects("9", "good"),
        average: 0,
        passed: true,
        observations: "Preparação para exames nacionais.",
        attendanceRate: 96,
        totalClasses: 200,
        attendedClasses: 192,
      },
      {
        year: "2023",
        grade: "8ª Classe",
        class: "8ºA",
        school: "Escola Secundária Aurora",
        subjects: generateSubjects("8", "good"),
        average: 0,
        passed: true,
        observations: "Bom desempenho geral.",
        attendanceRate: 94,
        totalClasses: 200,
        attendedClasses: 188,
      },
      {
        year: "2022",
        grade: "7ª Classe",
        class: "7ºB",
        school: "Escola Secundária Aurora",
        subjects: generateSubjects("7", "average"),
        average: 0,
        passed: true,
        observations: "Aprovado com média suficiente.",
        attendanceRate: 89,
        totalClasses: 200,
        attendedClasses: 178,
      },
      {
        year: "2021",
        grade: "6ª Classe",
        class: "6ºA",
        school: "Colégio Esperança",
        subjects: generateSubjects("6", "good"),
        average: 0,
        passed: true,
        observations: "Transferência de escola bem sucedida.",
        attendanceRate: 92,
        totalClasses: 200,
        attendedClasses: 184,
      },
    ],
    issuedDocuments: [
      {
        id: "doc6",
        type: "transcript",
        title: "Histórico Escolar Completo",
        issuedDate: new Date("2024-01-15"),
        withGrades: true,
      },
    ],
  },
  {
    id: "5",
    name: "Beatriz Rodrigues Costa",
    birthDate: new Date("2012-09-12"),
    gender: "F",
    nationality: "Angolana",
    documentNumber: "005678901LA049",
    documentType: "Bilhete de Identidade",
    address: "Rua da Liberdade, nº 55, Kilamba, Luanda",
    phone: "+244 927 890 123",
    email: "beatriz.costa@email.com",
    parentName: "Sofia Costa",
    parentPhone: "+244 916 789 012",
    parentEmail: "sofia.costa@email.com",
    enrollmentDate: new Date("2020-02-01"),
    currentSchool: "Colégio Pitágoras",
    currentGrade: "5ª Classe",
    currentClass: "5ºA",
    studentNumber: "2020/005678",
    academicHistory: [
      {
        year: "2024",
        grade: "5ª Classe",
        class: "5ºA",
        school: "Colégio Pitágoras",
        subjects: generateSubjects("5", "average"),
        average: 0,
        passed: true,
        observations: "Transição para o segundo ciclo.",
        attendanceRate: 91,
        totalClasses: 200,
        attendedClasses: 182,
      },
      {
        year: "2023",
        grade: "4ª Classe",
        class: "4ºB",
        school: "Colégio Pitágoras",
        subjects: generateSubjects("4", "good"),
        average: 0,
        passed: true,
        observations: "Bom aproveitamento no ensino primário.",
        attendanceRate: 93,
        totalClasses: 180,
        attendedClasses: 167,
      },
      {
        year: "2022",
        grade: "3ª Classe",
        class: "3ºA",
        school: "Colégio Pitágoras",
        subjects: generateSubjects("3", "good"),
        average: 0,
        passed: true,
        observations: "Desenvolvimento positivo.",
        attendanceRate: 95,
        totalClasses: 180,
        attendedClasses: 171,
      },
      {
        year: "2021",
        grade: "2ª Classe",
        class: "2ºB",
        school: "Colégio Pitágoras",
        subjects: generateSubjects("2", "average"),
        average: 0,
        passed: true,
        observations: "Adaptação ao ambiente escolar.",
        attendanceRate: 90,
        totalClasses: 180,
        attendedClasses: 162,
      },
      {
        year: "2020",
        grade: "1ª Classe",
        class: "1ºA",
        school: "Colégio Pitágoras",
        subjects: generateSubjects("1", "average"),
        average: 0,
        passed: true,
        observations: "Iniciação escolar durante a pandemia.",
        attendanceRate: 85,
        totalClasses: 150,
        attendedClasses: 128,
      },
    ],
    issuedDocuments: [
      {
        id: "doc7",
        type: "declaration",
        title: "Declaração de Matrícula 2024",
        issuedDate: new Date("2024-02-20"),
        withGrades: false,
      },
    ],
  },
];

// Recalculate averages for all students
mockStudentProfiles.forEach((student) => {
  student.academicHistory.forEach((year) => {
    year.average = calculateAverage(year.subjects);
  });
});

export const getStudentById = (id: string): StudentFullProfile | undefined => {
  return mockStudentProfiles.find((student) => student.id === id);
};

export const searchStudentByName = (name: string): StudentFullProfile[] => {
  return mockStudentProfiles.filter((student) =>
    student.name.toLowerCase().includes(name.toLowerCase())
  );
};